# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks


# Setup
title:            mmBs
tagline:          'Devs Blog'
description:      'mmBs Blog'
url:              'https://mmbs.github.io'
baseurl:          /


# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar:

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: mmbs
  instagram:
  linkedin: mmbialas
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: mmbialas
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: u/0/111871061538679318016 # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-2110



author:
  name:           'Michal Bialas'
  url:            https://twitter.com/mmbialas

paginate:         4

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mmbs

gems:
  [jekyll-paginate]
 # This will require each of these gems automatically.

 # Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
